## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Simon Yost"
copyright = "{year}"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "public"

# Remote
#baseURL = "https://simonyost.com"
#publishDir = "//centos/sites/hugodev/hugostory/"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "section"]
googleAnalytics = "G-ZK9C0PHGJK"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "When execution slows as systems scale, more resources make it worse. A systems-level advisory for leaders facing rising complexity, cost, and decision latency."
  logo = "images/simon_010sq.jpg"
  favicon = false

[Params.social]
  # github = "https://github.com/caressofsteel/"
  # twitter = "https://twitter.com/caressofsteel_"
  email = "simon@simonyost.com"
  instagram = "https://instagram.com/simon.yost"
  linkedin = "https://www.linkedin.com/in/simonyost/"
  # telegram = "https://telegram.org"

[Params.asset]
  fontawesome_css = ["css/fontawesome-all.min.css"]
  fontawesome_js = ["js/fontawesome-all.min.js"]